### ISSUE TITLE
Compatibility with compressibleInterFoam?!

### ISSUE THREAD

**Issue by jrdkr** [Venky-94/interFoamMod#1]
Thanks for sharing your code!!!
At present Iam struggling with my modified version of compressibleInterFoam for simulating polymer flows/injection molding process. Due to the relatively high viscosity of polymer (especially in areas near to the cooled cavities) simulation blows up. At present this can oly be resolved by applying really low time steps / CFLNumbers, which extremly raises computation times... I think the main issue lies in the high viscosity ratio (stiff problem). You think your approach can takle this? As far as I see, only modifications are made for the interfaceProperties-Class? So there must be compatibility with compressibleInterFoam since they both use same files for interfaceProps? Or do I have to make more modifications in the solver itself?

Sorry for this long text but I am really stuck on this problem for a few months...

**Comment by Venky-94** [comment]
Hey, yes in theory it should not have any problem in being adapted to compressibleInterFoam. Just a heads-up though, the changes present in interfaceProps are for the surface tension smoothing only and the viscosity correction in itself is done by adapting an exponential averaging for calculating the mixture fluid properties (density and viscosity) instead of the default linear interpolation in VOF. The changes are simple one line changes and can be found under "createFields.H, alphaEqnSubcycle.H, and userincompressibleTwoPhaseFlow". Please check the paper for details on the advantage. All the best for your work and let me know how it works out for you!
